# Generated by Django 4.2.1 on 2023-06-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_realty_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='surname',
            field=models.TextField(null=True),
        ),
    ]
