# Generated by Django 4.2.1 on 2023-06-07 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_manager_email_manager_phone_manager_surname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='surname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
