# Generated by Django 4.2.1 on 2023-06-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_realty_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
