# Generated by Django 4.2.1 on 2023-06-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_manager_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='realty',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Users'),
        ),
    ]
