# Generated by Django 4.2.2 on 2023-07-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayavki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zayavka',
            name='manager_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
